# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormMenu(object):
    def setupUi(self, FormMenu):
        FormMenu.setObjectName("FormMenu")
        FormMenu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(FormMenu)
        self.centralwidget.setObjectName("centralwidget")

        # Añadir etiqueta de bienvenida
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(200, 50, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")

        # Añadir etiqueta de pregunta
        self.label_question = QtWidgets.QLabel(self.centralwidget)
        self.label_question.setGeometry(QtCore.QRect(200, 150, 400, 50))
        font.setPointSize(16)
        self.label_question.setFont(font)
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setObjectName("label_question")

        FormMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FormMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuHolala = QtWidgets.QMenu(self.menubar)
        self.menuHolala.setObjectName("menuHolala")
        self.menuDesencriptar = QtWidgets.QMenu(self.menubar)
        self.menuDesencriptar.setObjectName("menuDesencriptar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuSalir = QtWidgets.QMenu(self.menubar)
        self.menuSalir.setObjectName("menuSalir")
        FormMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FormMenu)
        self.statusbar.setObjectName("statusbar")
        FormMenu.setStatusBar(self.statusbar)
        self.actionEncriptar = QtWidgets.QAction(FormMenu)
        self.actionEncriptar.setObjectName("actionEncriptar")
        self.menuHolala.addAction(self.actionEncriptar)
        self.menubar.addAction(self.menuHolala.menuAction())
        self.menubar.addAction(self.menuDesencriptar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menubar.addAction(self.menuSalir.menuAction())

        self.retranslateUi(FormMenu)
        QtCore.QMetaObject.connectSlotsByName(FormMenu)

    def retranslateUi(self, FormMenu):
        _translate = QtCore.QCoreApplication.translate
        FormMenu.setWindowTitle(_translate("FormMenu", "MainWindow"))
        self.label_welcome.setText(_translate("FormMenu", "Bienvenido al sistema SIUU"))
        self.label_question.setText(
            _translate("FormMenu", "¿Qué desea realizar, amigazo?")
        )
        self.menuHolala.setTitle(_translate("FormMenu", "Encriptar"))
        self.menuDesencriptar.setTitle(_translate("FormMenu", "Desencriptar"))
        self.menuAyuda.setTitle(_translate("FormMenu", "Ayuda"))
        self.menuSalir.setTitle(_translate("FormMenu", "Salir"))
        self.actionEncriptar.setText(_translate("FormMenu", "Encriptar"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FormMenu = QtWidgets.QMainWindow()
    ui = Ui_FormMenu()
    ui.setupUi(FormMenu)
    FormMenu.show()
    sys.exit(app.exec_())
