# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):  
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 669)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(100, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(90, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(80, 400, 191, 51))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/siu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setAutoRepeatDelay(303)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(60, 60, 501, 191))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/welcome.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/no.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setAutoRepeatDelay(303)
        self.pushButton_2.setObjectName("pushButton_2")
        self.txtUser = QtWidgets.QLineEdit(MainWindow)  
        self.txtUser.setGeometry(QtCore.QRect(230, 260, 151, 31))
        self.txtUser.setObjectName("txtUser")  
        self.txtPassword = QtWidgets.QLineEdit(MainWindow) 
        self.txtPassword.setGeometry(QtCore.QRect(230, 320, 151, 31))
        self.txtPassword.setObjectName("txtPassword")  

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "Usuario:"))
        self.label_2.setText(_translate("MainWindow", "¡ Holiwiwiriski !"))
        self.label_3.setText(_translate("MainWindow", "Contraseña:"))
        self.pushButton.setText(_translate("MainWindow", "Inicias Sesion"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_Dialog()  
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())